FROM node:20-alpine

WORKDIR /app

# Build arguments
ARG NEXT_PUBLIC_SANITY_PROJECT_ID
ARG NEXT_PUBLIC_SANITY_DATASET
ARG NEXT_PUBLIC_SANITY_API_VERSION
ARG NEXT_PUBLIC_SIGNIN_URL
ARG ZAPIER_CONTACT_WEBHOOK_URL
ARG NEXT_PUBLIC_API_URL

# Inject into environment during build
ENV NEXT_PUBLIC_SANITY_PROJECT_ID=$NEXT_PUBLIC_SANITY_PROJECT_ID
ENV NEXT_PUBLIC_SANITY_DATASET=$NEXT_PUBLIC_SANITY_DATASET
ENV NEXT_PUBLIC_SANITY_API_VERSION=$NEXT_PUBLIC_SANITY_API_VERSION
ENV NEXT_PUBLIC_SIGNIN_URL=$NEXT_PUBLIC_SIGNIN_URL
ENV ZAPIER_CONTACT_WEBHOOK_URL=$ZAPIER_CONTACT_WEBHOOK_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]